# Taken from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels build

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.0.1
        env:
          CIBW_PLATFORM: linux
          CIBW_ARCHS: x86_64
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: "pip install -r requirements_dev.txt --user && pip install ."
          CIBW_BUILD: "cp39-manylinux_x86_64"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
