# Taken from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels build

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.0.1
        env:
          CIBW_BUILD_VERBOSITY: 3
          CIBW_PROJECT_REQUIRES_PYTHON: "==3.9"
          CIBW_BEFORE_BUILD: "pip install -r requirements_dev.txt --user && pip install ."
          CIBW_BEFORE_BUILD_MACOS: "brew install llvm libomp"
          CIBW_BUILD: "cp39-x86_64"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
