# Taken from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels build

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_PLATFORM: auto
          CIBW_ARCHS: auto64
          CIBW_SKIP: cp*-musllinux*
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: "pip install -r requirements_dev.txt --user && pip install ."
          CIBW_BEFORE_BUILD_MACOS: "brew install gcc && pip install -r requirements_dev.txt --user && pip install ."
          CIBW_BUILD: cp38-* cp39-* cp310-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
          -   uses: actions/checkout@v2

          -   uses: actions/setup-python@v2
              name: Install Python
              with:
                  python-version: '3.9'

          -   name: Build sdist
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements_dev.txt
                python setup.py sdist

          -   uses: actions/upload-artifact@v2
              with:
                  path: dist/*.tar.gz
